flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: core
      carryforward: true
      statuses:
        - type: project
          target: auto

coverage:
  status:
    patch: off
